services:

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"     # 6380 on host so it doesn't clash with your local Redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  ratesentry_1:
    build: .
    ports:
      - "8001:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RATE_LIMIT_MAX_REQUESTS=100
      - RATE_LIMIT_WINDOW_SECONDS=60
    depends_on:
      redis:
        condition: service_healthy

  ratesentry_2:
    build: .
    ports:
      - "8002:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RATE_LIMIT_MAX_REQUESTS=100
      - RATE_LIMIT_WINDOW_SECONDS=60
    depends_on:
      redis:
        condition: service_healthy

  ratesentry_3:
    build: .
    ports:
      - "8003:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RATE_LIMIT_MAX_REQUESTS=100
      - RATE_LIMIT_WINDOW_SECONDS=60
    depends_on:
      redis:
        condition: service_healthy